import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import About from '@/components/About' /* i guess the @ works instead of the .. */
import Skills from '@/components/Skills'

export default function Home() {
  return (
    <>
        <Head>
            <title>Leonardo Curdi</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.png" />
        </Head>

        <Navbar />
        <Main />
        <About />
        <Skills />

    </>
  )
}
